export const INDUSTRIES = [
  "Business / Company",
  "E-commerce",
  "E-commerce & Retail",
  "Software & Technology",
  "SaaS & Technology",
  "Financial Services",
  "Healthcare",
  "Education",
  "Real Estate",
  "Non-profit / Organization",
  "Travel & Hospitality",
  "Professional Services",
  "Logistics",
  "Telecommunications",
  "Media & Entertainment",
  "Other",
] as const;

export const COUNTRIES = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "France",
  "Spain",
  "Netherlands",
  "United Arab Emirates",
  "Saudi Arabia",
  "India",
  "Pakistan",
  "Singapore",
  "Nigeria",
  "South Africa",
  "Brazil",
  "Mexico",
  "Japan",
] as const;

export const TIMEZONES = [
  "UTC-08:00 — Pacific Time",
  "UTC-05:00 — Eastern Time",
  "UTC-03:00 — São Paulo",
  "UTC+00:00 — London",
  "UTC+01:00 — Central European Time",
  "UTC+03:00 — Riyadh / Moscow",
  "UTC+04:00 — Dubai",
  "UTC+05:00 — Karachi",
  "UTC+05:30 — India Standard Time",
  "UTC+08:00 — Singapore",
  "UTC+09:00 — Tokyo",
  "UTC+10:00 — Sydney",
] as const;

export const BRAND_COLOR_SWATCHES = [
  "#2563EB",
  "#0F172A",
  "#06B6D4",
  "#10B981",
  "#F59E0B",
  "#EF4444",
  "#7C3AED",
  "#DB2777",
];
